# -*- coding: utf-8 -*-

feat_url = "http://dnd5e.wikia.com/wiki/Feats#"

feat_list = [
    "Actor",
    "Athlete",
    "Alert",
    "Charger",
    "Defensive Duelist",
    "Dual Wielder",
    "Dungeon Delver",
    "Durable",
    "Elemental Adept",
    "Grappler",
    "Great Weapon Master",
    "Healer",
    "Inspiring Leader",
    "Keen Mind",
    "Linguist",
    "Lucky",
    "Mage Slayer",
    "Magic Initiate",
    "Martial Adept",
    "Mobile",
    "Mounted Combatant",
    "Observant",
    "Resilient",
    "Ritual Caster",
    "Savage Attacker",
    "Sentinel",
    "Sharpshooter",
    "Skilled",
    "Skulker",
    "Spell Sniper",
    "Tough",
    "War Caster",
    "Blade Mastery",
    "Crossbow Expert",
    "Fell Handed",
    "Flail Mastery",
    "Polearm Master",
    "Shield Master",
    "Spear Mastery",
    "Tavern Brawler",
    "Weapon Master",
    "Lightly Armored",
    "Moderately Armored",
    "Medium Armor Master",
    "Heavily Armored",
    "Heavy Armor Master",
    "Acrobat",
    "Animal Handler",
    "Arcanist",
    "Brawny",
    "Diplomat",
    "Empathic",
    "Historian",
    "Investigator",
    "Medic",
    "Menacing",
    "Naturalist",
    "Perceptive",
    "Performer",
    "Quick-Fingered",
    "Silver-Tongued",
    "Stealthy",
    "Survivalist",
    "Theologian",
    "Alchemist",
    "Burglar",
    "Gourmand",
    "Master of Disguise",
    "Barbed Hide",
    "Bountiful Luck",
    "Critter Friend",
    "Dragon Fear",
    "Dragon Hide",
    "Dragon Wings",
    "Drow High Magic",
    "Dwarven Fortitude",
    "Elven Accuracy",
    "Everybody's Friend",
    "Fade Away",
    "Fey Teleportation",
    "Flames of Phlegethos",
    "Grudge-Bearer",
    "Human Determination",
    "Infernal Constitution",
    "Orcish Aggression",
    "Orcish Fury",
    "Prodigy",
    "Second Chance",
    "Squat Nimbleness",
    "Svirfneblin Magic",
    "Vampiric Exultation",
    "Wonder Maker",
    "Wood Elf Magic",
    "Aberrant Dragonmark",
    "Greater Dragonmark",
    "Quicksmithing",
    "Revenant Blade",
    "Servo Crafting"
]
